spring:
  application:
    name: payment-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_gateway
    username: gateway
    password: gateway_pass
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  threads:
    virtual:
      enabled: true   # Java 21 Project Loom — one line enables virtual threads

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:this-is-a-super-secure-and-ultra-long-secret-key-for-marianna-payment-gateway-2026=}
  expiration-ms: 3600000

auth:
  api-key: ${AUTH_API_KEY:local-dev-only}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.marianna.gateway: DEBUG
